FROM python:3.12.12-slim-bookworm

WORKDIR /backapp

RUN apt-get update

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload" ]
