import PublicHeader from "../Layouts/PublicHeader"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function PublicLayout({
    children,
}) {
    return (
        <>
            <PublicHeader />
            {children}
        </>
    )
}
