"""add statuses table

Revision ID: dfdd3a0382aa
Revises:
Create Date: 2026-04-14 12:01:26.719413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfdd3a0382aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    status_table = sa.table(
        "statuses",
        sa.column("code", sa.String()),
        sa.column("label", sa.String()),
    )

    op.bulk_insert(
        status_table,
        [
            {"code": "want_to_watch", "label": "見たい"},
            {"code": "watching", "label": "鑑賞中"},
            {"code": "watched", "label": "鑑賞済み"},
        ],
    )

    op.create_index(op.f("ix_statuses_code"), "statuses", ["code"], unique=True)
    op.add_column("movies", sa.Column("status_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "movies", "statuses", ["status_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="foreignkey")
    op.drop_column("movies", "status_id")
    op.drop_index(op.f("ix_statuses_code"), table_name="statuses")
    op.drop_table("statuses")
    # ### end Alembic commands ###
